### ISSUE TITLE
Some strings are changed inside sage environment

### ISSUE THREAD

**Issue by danm0nster** [nielsthl/QaDiL#20]
In R the use of the `$`-character, e.g. to address a column in a data frame, presents a similar problem because QaDiL converts the  string following the `$`-character to mathematics.

If there is one (or an uneven number) of `$`-characters in the code it will cause QaDiL to hang, and if there is an even number it will just corrupt the R code.

Here is a minimal example that will produce an error when using R inside a sage environment (requires the sagecell HTML code to be modified to use R).

```
\begin{sage}
  d <- data.frame(X = 1:10, Y = 11:20)
  x <- d$X
  y <- d$Y
  print(y-x)
\end{sage}
```

Here is a workaround that produces the expected output because it avoids using `$`.

```
\begin{sage}
  library(dplyr)
  d <- data.frame(X = 1:10, Y = 11:20)
  x <- d %>% pull(X)
  y <- d %>% pull(Y)
  print(y-x)
\end{sage}
```

**Comment by nielsthl** [comment]
Done by pull request #25.
