### ISSUE TITLE
Footnotes are written after text, not as a hover

### ISSUE THREAD

**Issue by danm0nster** [nielsthl/QaDiL#21]
The example below is taken from the documentation: https://edtech.dk/QaDiL/functions.html

The hover text appears right after the text it is supposed to be a note for.

![Screenshot 2022-06-23 at 17 25 48](https://user-images.githubusercontent.com/16464590/175336180-2f15a1a4-50db-4468-a119-a7336c8982c4.png)

**Comment by nielsthl** [comment]
Thanks! This is due to conflicts between the old footnote class and the new bubble class. This has been fixed. An updated manual is forthcoming.
