### ISSUE TITLE
Tokenization error using TeX spacing command \;

### ISSUE THREAD

**Issue by danm0nster** [nielsthl/QaDiL#38]
When using `\;` for spacing in equations, e.g.,
```
$$
        f(x, y) = xy^{\frac{2}{3}}, \quad x > 0, \; y > 0
$$
```
QaDiL produces an error in the tokenizer:

```
AttributeError: 'TokenType' object has no attribute 'rege'
```

**Comment by nielsthl** [comment]
Thanks. An addition of just the one character `;` in `Tokens.py` fixes this.
