### ISSUE TITLE
Embedding interactive graphics without sage editor window

### ISSUE THREAD

**Issue by danm0nster** [nielsthl/QaDiL#8]
In addition to the standard Sage Cell it would be nice to be able to include a figure (without the ability to input code).  It would be even nicer to be able to include sliders or input boxes to change values of parameters. An example (using Geogebra) can be seen in the online book [Complex Analysis]( https://complex-analysis.com/). The [introduction]( https://complex-analysis.com/content/brief_history.html) has an illustrative example.

This could be both using Sage and Geogebra. For Geogebra, it seems necessary to [upload the code](https://wiki.geogebra.org/en/Embedding_in_Webpages) to geogebra.com. 

For Sage Math, it can already be done with `\begin{sage} ... \end{sage}` and the only thing I miss is how to turn off the editor. It seems to require including [`hide: ["editor"]`](https://github.com/sagemath/sagecell/blob/master/doc/embedding.rst#hiding-sage-cell-elements) somewhere. I am not sure if this requires passing an option from the LaTeX source code through QaDiL or if a separate enviroment with matching CSS is needed. Probably both are possible.

Here is an example of what I would like, if I can just get rid of the editor.

<img width="686" alt="Screenshot 2021-08-30 at 14 15 49" src="https://user-images.githubusercontent.com/16464590/131337563-3ad7c409-84f3-4692-9792-87dcf4656a8d.png">

**Comment by danm0nster** [comment]
One more thing: To get the desired functionality the cell would have to auto-execute. This [seems to be doable](https://stackoverflow.com/questions/31739053/auto-activating-embedded-sage-cell).

```
sagecell.makeSagecell({inputLocation:  '#mycell',
                       template:       sagecell.templates.minimal,
                       hide: ["editor","evalButton"],
                       autoeval: true});
```

**Comment by nielsthl** [comment]
Settings for `Sage` are defined in `QaDiL/qadil/htmlinclude/sagecell`:
```
<script src="https://sagecell.sagemath.org/static/embedded_sagecell.js"></script>

<script>
  window.MathJax = 1 /* Disable MathJax */
  sagecell.makeSagecell({
  inputLocation: ".sage",
  evalButtonText: "Compute",
  linked: true,
  languages : ["sage", "python"],
  hide : ["permalink"] 
  });
</script>
```

**Comment by danm0nster** [comment]
Aha! Good to know.

So to change any of those settings it would currently affect the whole site/book, right?

Is there a way it could be generated dynamically, so that settings could be specified for each individual cell, independently from the rest?

**Comment by nielsthl** [comment]
Yes. These settings are for the book globally. I guess one could add some functionality to `\begin{sage} ... \end{sage}` to allow for local cell configurations. Perhaps optional parameters.

**Comment by danm0nster** [comment]
I put a new `sagecell.html` in a directory `local` and included it at the end of `genericdefs` like this:

```
\htmlpath{./local/}
\includehtml{sagecell}
```

The content of `local/sagecell.html` is:

```
<script src="https://sagecell.sagemath.org/static/embedded_sagecell.js"></script>

<script>
  window.MathJax = 1 /* Disable MathJax */
  sagecell.makeSagecell({
  inputLocation: ".sage",
  evalButtonText: "Start",
  linked: true,
  languages : ["sage", "python", "macaulay2"],
  hide : ["editor", "language", "permalink"]
  });
</script>
```
This works, but of course it makes it difficult to have sage cells with code shown and sage cells with code hidden in the same document.

So, it would still be nice to have an optional parameter like `\begin{sage}[hide]...\end{sage}` or a separate environment like `\begin{sagehidden}...\end{sagehidden}`.

Shall I look into this and make a pull request?

**Comment by nielsthl** [comment]
It actually seems that `\begin{sage} ... \end{sage}` has an optional parameter `showhide`, which hides the `sage` window in a button. Are you thinking of hiding the window completely with no button? Perhaps you can give an example of the use you have in mind.

**Comment by danm0nster** [comment]
I have solved this problem and will add the solution to the documentation.
