### ISSUE TITLE
Contents of \phantom is displayed when printing

### ISSUE THREAD

**Issue by gardeAU** [nielsthl/QaDiL#9]
When using \phantom to add spaces, it shows correctly in the HTML version, but when the HTML site is printed to paper or printed to PDF the contents of \phantom show up.

A minimal example is attached, where the corresponding tex-file contains:

$x + y \phantom{\text{ halløjsa! }} - z$

The attached test.pdf shows the page printed to PDF, while test2.pdf is saved using Chrome's "emulate CSS media type"-tool to show how the HTML version looks.

[test.pdf](https://github.com/nielsthl/QaDiL/files/7221056/test.pdf)
[test2.pdf](https://github.com/nielsthl/QaDiL/files/7221057/test2.pdf)

**Comment by FunByJohn** [comment]
If you add the following to `css/iLaTeXen.css`:
```
span[style*="transparent"] {
  visibility: hidden;
}
```
then it works for me when printing. It seems that elements on which `phantom` has been applied to have the css property `color: transparent`, and for some reason printing doesn't play well with this. But it works if we add `visiblity: hidden` as well!

**Comment by FunByJohn** [comment]
CSS fix is added to latest version
